<h2>¿Qué es design thinking?</h2>
<p>La traducción literal de Design thinking al castellano es “pensamiento de diseño” y se refiere a un proceso iterativo para entender a los usuarios y sus necesidades, retar los paradigmas establecidos y redefinir los problemas para encontrar soluciones y estrategias que puedan superar nuestro nivel inicial de entendimiento sobre un problema.</p>
<p>En términos más prácticos, design thinking es un proceso de pensamiento estructurado para diseñar productos y servicios que solucionen problemas o necesidades reales de los usuarios.</p>
<p>Design Thinking ofrece un enfoque orientado a generar soluciones en la manera de resolver los problemas que está siendo utilizado por las mejores universidades del mundo y por la mayoría de las empresas líderes en innovación, como Apple, Google, Airbnb, entre otras.</p>
<h2></span>¿Qué aporta el proceso de <em>design thinking</em>para pensar “fuera de la caja”?</h2>
<p>Al diseñar un producto o servicio, es común que los equipos de diseñadores, “por más innovadores y creativos”, caigan en las mismas ideas y les cueste generar nuevas propuestas para los problemas que buscan resolver.</p>
<figure class="wp-block-image size-large" style="margin: 0px 0px 1.5em; max-width: 100%; height: auto; color: #515151; font-family: Helvetica; font-size: 22px;"><img class="wp-image-97969 ls-is-cached lazyloaded" style="height: auto; max-width: 100%;" src="https://identidadydesarrollo.com/wp-content/uploads/2019/07/Piensa-fuera-de-la-caja.jpg" sizes="(max-width: 960px) 100vw, 960px" srcset="https://identidadydesarrollo.com/wp-content/uploads/2019/07/Piensa-fuera-de-la-caja.jpg 960w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Piensa-fuera-de-la-caja-300x169.jpg 300w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Piensa-fuera-de-la-caja-768x432.jpg 768w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Piensa-fuera-de-la-caja-400x225.jpg 400w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Piensa-fuera-de-la-caja-600x338.jpg 600w" alt="Piensa fuera de la caja con pensamiento de diseño" width="960" height="540" data-src="https://identidadydesarrollo.com/wp-content/uploads/2019/07/Piensa-fuera-de-la-caja.jpg" data-srcset="https://identidadydesarrollo.com/wp-content/uploads/2019/07/Piensa-fuera-de-la-caja.jpg 960w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Piensa-fuera-de-la-caja-300x169.jpg 300w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Piensa-fuera-de-la-caja-768x432.jpg 768w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Piensa-fuera-de-la-caja-400x225.jpg 400w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Piensa-fuera-de-la-caja-600x338.jpg 600w"></figure>
<p >Después de todo, los humanos generamos patrones y modelos de pensamiento basados en repeticiones y conocimientos previos.</p>
<p>Esto es natural, ya que nos ayuda a aplicar rápidamente las acciones y conocimientos previamente adquiridos a situaciones similares o familiares.</p>
<p>Sin embargo, estos patrones crean paradigmas que potencialmente nos afectan para desarrollar nuevas maneras de aproximarnos, ver, analizar, entender y resolver nuevos problemas o los mismos problemas de maneras más eficientes.</p>
<h2><span id="Resolver_problemas_y_generar_soluciones_a_necesidades" class="ez-toc-section"></span>Resolver problemas y generar soluciones a necesidades</h2>
<p>Cuando nos enfocamos en resolver los problemas de un usuario, de un grupo de usuarios o inclusive de una población, es importante tomar en cuenta que esas personas muy probablemente saben más sobre sus necesidades y sus problemas que nosotros mismos por más que hagamos investigaciones.</p>
<p>Esto es particularmente relevante cuando trabajamos en proyectos de desarrollo comunitario, cuando somos gestores o implementadores de un proyecto, debemos ser muy claros desde el principio que tenemos distintas perspectivas y experiencias, y son los propios actores de las comunidades quienes son expertos en sus ámbitos.</p>
<p>Desde esta perspectiva, los interventores externos no vienen a resolver los problemas porque saben más que la propia gente de la comunidad, sino que participan como socios y actores clave de su propio desarrollo.</p>
<p >Primero hay que pensar en las estrategias de alto nivel para después ir detallando cada parte del problema en soluciones más pequeñas y manejables.</p>
<p>¿Cuáles son las necesidades y cuáles son las limitantes que nos plantea el entorno para trabajar y orientar las posibles soluciones?</p>
<p>En el curso de <em >design thinking </em>de MIT, el equipo de diseñadores cuenta que si Henry Ford le hubiera preguntado a la gente lo que quería le hubieran dicho “quiero caballos más rápidos” y no necesariamente quiero llegar más rápido de un punto a otro, que sería la necesidad específica que decidió abordar con la producción de automóviles.</p>
<p>Cuando le preguntas a un usuario lo que quiere debes prestar atención a las verdaderas necesidades y profundizar con observación y otros métodos de investigación para realmente llegar al fondo del asunto.</p>
<p >El objetivo fundamental del pensamiento de diseño, como ya vimos más arriba, está en encontrar soluciones a problemas, lo que por definición suele ser complejo, y dependiendo del tipo y magnitud del problema puede ser mucho más.</p>
<p >Por eso, una de las claves que debes tener como diseñador es la pasión y perseverancia para resolver el problema e inclusive aprender sobre nuevos campos de conocimiento que quizás ni siquiera tenías identificados.</p>
<h2>El proceso iterativo de Design Thinking</h2>
<p>Un proceso iterativo es aquel que, aunque está estructurado de manera lineal, regresa a los pasos y etapas anteriores para retroalimentar y mejorar el diseño conforme se avanza en el desarrollo del proyecto.</p>
<p>En este sentido, suele representarse de manera circular o tener varios ciclos internos en las distintas etapas en las que se lleva a cabo.</p>
<figure class="wp-block-image size-large" style="margin: 0px 0px 1.5em; max-width: 100%; height: auto; color: #515151; font-family: Helvetica; font-size: 22px;"><img class="wp-image-97938 lazyloaded" style="height: auto; max-width: 100%;" src="https://identidadydesarrollo.com/wp-content/uploads/2019/07/Proceso-iterativo-de-design-thinking-1024x689.png" sizes="(max-width: 1024px) 100vw, 1024px" srcset="https://identidadydesarrollo.com/wp-content/uploads/2019/07/Proceso-iterativo-de-design-thinking-1024x689.png 1024w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Proceso-iterativo-de-design-thinking-300x202.png 300w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Proceso-iterativo-de-design-thinking-768x517.png 768w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Proceso-iterativo-de-design-thinking-1536x1033.png 1536w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Proceso-iterativo-de-design-thinking-400x269.png 400w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Proceso-iterativo-de-design-thinking-600x404.png 600w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Proceso-iterativo-de-design-thinking-272x182.png 272w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Proceso-iterativo-de-design-thinking.png 1702w" alt="Qué es el proceso iterativo circular de design thinking" width="1024" height="689" data-src="https://identidadydesarrollo.com/wp-content/uploads/2019/07/Proceso-iterativo-de-design-thinking-1024x689.png" data-srcset="https://identidadydesarrollo.com/wp-content/uploads/2019/07/Proceso-iterativo-de-design-thinking-1024x689.png 1024w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Proceso-iterativo-de-design-thinking-300x202.png 300w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Proceso-iterativo-de-design-thinking-768x517.png 768w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Proceso-iterativo-de-design-thinking-1536x1033.png 1536w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Proceso-iterativo-de-design-thinking-400x269.png 400w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Proceso-iterativo-de-design-thinking-600x404.png 600w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Proceso-iterativo-de-design-thinking-272x182.png 272w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Proceso-iterativo-de-design-thinking.png 1702w"></figure>
<h2>¿Cuáles son los 6 pasos de design thinking?</h2>
<p>Cómo en todos los campos, hay distintas variantes de las metodologías y procesos, aunque la mayoría suelen ser similares y todas engloban los mismos principios.</p>
<p>Uno de los enfoques más populares es el que se utiliza en el Instituto de Diseño de Stanford, también conocido como d.school, que es una de las instituciones a la vanguardia en promover el aprendizaje del design thinking.</p>
<p>Los colaboradores de esta institución han trabajado con este proceso desde la década de los 70 y continúan generando innovaciones a través de su aplicación.</p>
<p>Inicialmente estaba estructurado en cinco etapas principales, aunque las aproximaciones más nuevas están incorporando la sexta fase que se refiere propiamente a la implementación resultado del proceso de diseño.</p>
<p>Otra manera de ver el proceso además del diagrama circular que vimos arriba es de manera horizontal con conexiones entre los distintos pasos.</p>
<figure class="wp-block-image size-large" style="margin: 0px 0px 1.5em; max-width: 100%; height: auto; color: #515151; font-family: Helvetica; font-size: 22px;"><img class="wp-image-97948 lazyloaded" style="height: auto; max-width: 100%;" src="https://identidadydesarrollo.com/wp-content/uploads/2019/07/Design-thinking-diagrama-horizontal-1024x350.png" sizes="(max-width: 1024px) 100vw, 1024px" srcset="https://identidadydesarrollo.com/wp-content/uploads/2019/07/Design-thinking-diagrama-horizontal-1024x350.png 1024w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Design-thinking-diagrama-horizontal-300x102.png 300w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Design-thinking-diagrama-horizontal-768x262.png 768w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Design-thinking-diagrama-horizontal-1536x525.png 1536w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Design-thinking-diagrama-horizontal-400x137.png 400w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Design-thinking-diagrama-horizontal-600x205.png 600w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Design-thinking-diagrama-horizontal.png 1880w" alt="Qué es el diagrama horizontal de design thinking" width="1024" height="350" data-src="https://identidadydesarrollo.com/wp-content/uploads/2019/07/Design-thinking-diagrama-horizontal-1024x350.png" data-srcset="https://identidadydesarrollo.com/wp-content/uploads/2019/07/Design-thinking-diagrama-horizontal-1024x350.png 1024w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Design-thinking-diagrama-horizontal-300x102.png 300w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Design-thinking-diagrama-horizontal-768x262.png 768w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Design-thinking-diagrama-horizontal-1536x525.png 1536w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Design-thinking-diagrama-horizontal-400x137.png 400w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Design-thinking-diagrama-horizontal-600x205.png 600w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Design-thinking-diagrama-horizontal.png 1880w"></figure>
<p>Los seis pasos de >Desing Thinking</p>
<ol>
<li style="border: 0px; margin: 0px; padding: 0px;">Empatiza</li>
<li style="border: 0px; margin: 0px; padding: 0px;">Define</li>
<li style="border: 0px; margin: 0px; padding: 0px;">Idea</li>
<li style="border: 0px; margin: 0px; padding: 0px;">Prototipa</li>
<li style="border: 0px; margin: 0px; padding: 0px;">Prueba</li>
<li style="border: 0px; margin: 0px; padding: 0px;">Implementa</li>
</ol>
<h3 style="border: 0px; margin: 0px 0px 20px; padding: 0px; font-family: Helvetica; font-size: 26px; font-weight: 400; line-height: 1.2em; color: #515151;"><span id="1_Empatiza_(Descubre)" class="ez-toc-section" style="border: 0px; margin: 0px; padding: 0px;"></span>1. Empatiza (Descubre)</h3>
<figure class="wp-block-image size-large" style="margin: 0px 0px 1.5em; max-width: 100%; height: auto; color: #515151; font-family: Helvetica; font-size: 22px;"><img class="wp-image-97951 lazyloaded" style="height: auto; max-width: 100%;" src="https://identidadydesarrollo.com/wp-content/uploads/2019/07/Que%CC%81-es-el-Paso-1-de-design-thinking-empatiza-1024x610.jpg" sizes="(max-width: 1024px) 100vw, 1024px" srcset="https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-Paso-1-de-design-thinking-empatiza-1024x610.jpg 1024w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-Paso-1-de-design-thinking-empatiza-300x179.jpg 300w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-Paso-1-de-design-thinking-empatiza-768x457.jpg 768w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-Paso-1-de-design-thinking-empatiza-400x238.jpg 400w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-Paso-1-de-design-thinking-empatiza-600x357.jpg 600w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-Paso-1-de-design-thinking-empatiza.jpg 1026w" alt="Qué es el Paso 1 de design thinking empatiza" width="1024" height="610" data-src="https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-Paso-1-de-design-thinking-empatiza-1024x610.jpg" data-srcset="https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-Paso-1-de-design-thinking-empatiza-1024x610.jpg 1024w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-Paso-1-de-design-thinking-empatiza-300x179.jpg 300w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-Paso-1-de-design-thinking-empatiza-768x457.jpg 768w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-Paso-1-de-design-thinking-empatiza-400x238.jpg 400w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-Paso-1-de-design-thinking-empatiza-600x357.jpg 600w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-Paso-1-de-design-thinking-empatiza.jpg 1026w"></figure>
<p>El punto inicial del proceso se orienta en comprender las necesidades de los usuarios, que pueden ser varios.</p>
<p>Esto quiere decir, realmente ponerse en el lugar de las personas, cómo es su entorno, cuáles son sus dolencias o carencias y también sus alegrías y pasiones.</p>
<p>Una de las mejores maneras para hacer esto es acercarse directamente con los usuarios y establecer entrevistas o conversaciones abiertas para comprender sus necesidades desde una perspectiva personal.</p>
<p>Como en todas las etapas del proceso, es importante no tener preconcepciones.</p>
<h3>2. Define (Enfoca)</h3>
<figure class="wp-block-image size-large" style="margin: 0px 0px 1.5em; max-width: 100%; height: auto; color: #515151; font-family: Helvetica; font-size: 22px;"><img class="wp-image-97963 lazyloaded" style="height: auto; max-width: 100%;" src="https://identidadydesarrollo.com/wp-content/uploads/2019/07/Que%CC%81-es-el-paso-2-de-design-thinking-define-1024x625.png" sizes="(max-width: 1024px) 100vw, 1024px" srcset="https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-2-de-design-thinking-define-1024x625.png 1024w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-2-de-design-thinking-define-300x183.png 300w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-2-de-design-thinking-define-768x469.png 768w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-2-de-design-thinking-define-1536x938.png 1536w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-2-de-design-thinking-define-2048x1251.png 2048w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-2-de-design-thinking-define-400x244.png 400w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-2-de-design-thinking-define-600x366.png 600w" alt="Qué es el paso 2 de design thinking define" width="1024" height="625" data-src="https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-2-de-design-thinking-define-1024x625.png" data-srcset="https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-2-de-design-thinking-define-1024x625.png 1024w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-2-de-design-thinking-define-300x183.png 300w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-2-de-design-thinking-define-768x469.png 768w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-2-de-design-thinking-define-1536x938.png 1536w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-2-de-design-thinking-define-2048x1251.png 2048w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-2-de-design-thinking-define-400x244.png 400w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-2-de-design-thinking-define-600x366.png 600w"></figure>
<p>Es momento de acotar las necesidades y problemáticas que vamos a enfocar para generar posibles soluciones.</p>
<p>En esta fase, se escribe y categoriza toda la información recopilada durante la etapa de empatía. Escribe todas las preguntas que puedas relacionar con las problemáticas y necesidades que identificaste a través del conocimiento que has obtenido sobre el usuario.</p>
<p>En la definición del problema es importante profundizar en las causas y efectos, así como las soluciones actuales que se están utilizando para abordar el problema.</p>
<p>Una metodología que puede ser muy útil es la del árbol de problemas y soluciones que permite visualizar de manera gráfica los componentes de problemas complejos y abordarlos poco a poco. Esto te ayudará a identificar si existe algún problema anterior que está causando buena parte del problema y que al resolverlo quizás ni siquiera sea relevante el problema que inicialmente estás enfocando.</p>
<p>Ya durante esta etapa podrás ir identificando qué aportaría más valor para abordar desde nuevas perspectivas para crear nuevas soluciones durante los siguientes pasos del proceso.</p>
<h3><span id="3_Idea_(Imagina)" class="ez-toc-section" style="border: 0px; margin: 0px; padding: 0px;"></span>3. Idea (Imagina)</h3>
<figure class="wp-block-image size-large" style="margin: 0px 0px 1.5em; max-width: 100%; height: auto; color: #515151; font-family: Helvetica; font-size: 22px;"><img class="wp-image-97964 lazyloaded" style="height: auto; max-width: 100%;" src="https://identidadydesarrollo.com/wp-content/uploads/2019/07/Que%CC%81-es-el-paso-3-de-design-thinking-idea-1024x610.jpg" sizes="(max-width: 1024px) 100vw, 1024px" srcset="https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-3-de-design-thinking-idea-1024x610.jpg 1024w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-3-de-design-thinking-idea-300x179.jpg 300w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-3-de-design-thinking-idea-768x457.jpg 768w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-3-de-design-thinking-idea-400x238.jpg 400w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-3-de-design-thinking-idea-600x357.jpg 600w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-3-de-design-thinking-idea.jpg 1026w" alt="" width="1024" height="610" data-src="https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-3-de-design-thinking-idea-1024x610.jpg" data-srcset="https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-3-de-design-thinking-idea-1024x610.jpg 1024w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-3-de-design-thinking-idea-300x179.jpg 300w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-3-de-design-thinking-idea-768x457.jpg 768w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-3-de-design-thinking-idea-400x238.jpg 400w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-3-de-design-thinking-idea-600x357.jpg 600w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-3-de-design-thinking-idea.jpg 1026w"></figure>
<p>Ya tienes un marco de referencia sobre el usuario y la definición del problema, pero todavía no hay claridad acerca de cómo vamos a resolver este problema.</p>
<p>El objetivo de esta etapa es imaginar o generar tantas ideas como puedas para orientar la solución de los problemas identificados.</p>
<p>Es realmente importante abordar las necesidades con una mente abierta y explorar todas las opciones sin casarse con una posible solución desde el principio, ya que podríamos estarnos perdiendo de nuevas fórmulas y maneras de hacer las cosas.</p>
<p>Por más locas que parezcan las ideas, hay que considerarlas, a veces, las que a primera vista parecen extravagantes o poco viables son las que te permitirán generar una verdadera innovación y generar las soluciones de mayor valor.</p>
<p><span style="border: 0px; margin: 0px; padding: 0px; font-weight: bold;">Tip pro:</span>Procura divertirte, enfoca este ejercicio como un juego de creatividad en conjunto con tu equipo o en su caso entre amigos.</p>
<h3>4. Prototipa (Construye)</h3>
<figure class="wp-block-image size-large" style="margin: 0px 0px 1.5em; max-width: 100%; height: auto; color: #515151; font-family: Helvetica; font-size: 22px;"><img class="wp-image-97967 lazyloaded" style="height: auto; max-width: 100%;" src="https://identidadydesarrollo.com/wp-content/uploads/2019/07/%C2%BFQue%CC%81-es-el-paso-4-de-design-thinking-prototipa-1024x610.jpg" sizes="(max-width: 1024px) 100vw, 1024px" srcset="https://identidadydesarrollo.com/wp-content/uploads/2019/07/¿Qué-es-el-paso-4-de-design-thinking-prototipa-1024x610.jpg 1024w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/¿Qué-es-el-paso-4-de-design-thinking-prototipa-300x179.jpg 300w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/¿Qué-es-el-paso-4-de-design-thinking-prototipa-768x457.jpg 768w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/¿Qué-es-el-paso-4-de-design-thinking-prototipa-400x238.jpg 400w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/¿Qué-es-el-paso-4-de-design-thinking-prototipa-600x357.jpg 600w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/¿Qué-es-el-paso-4-de-design-thinking-prototipa.jpg 1026w" alt="" width="1024" height="610" data-src="https://identidadydesarrollo.com/wp-content/uploads/2019/07/¿Qué-es-el-paso-4-de-design-thinking-prototipa-1024x610.jpg" data-srcset="https://identidadydesarrollo.com/wp-content/uploads/2019/07/¿Qué-es-el-paso-4-de-design-thinking-prototipa-1024x610.jpg 1024w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/¿Qué-es-el-paso-4-de-design-thinking-prototipa-300x179.jpg 300w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/¿Qué-es-el-paso-4-de-design-thinking-prototipa-768x457.jpg 768w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/¿Qué-es-el-paso-4-de-design-thinking-prototipa-400x238.jpg 400w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/¿Qué-es-el-paso-4-de-design-thinking-prototipa-600x357.jpg 600w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/¿Qué-es-el-paso-4-de-design-thinking-prototipa.jpg 1026w"></figure>
<p>Ya que tenemos nuestras grandes ideas sobre las posibles soluciones, nos ponemos a la obra para crear prototipos o modelos ejemplo.</p>
<p>Los prototipos son una manera de comunicar y compartir las ideas de una manera más estructurada.</p>
<p>El tipo de prototipo a crear será muy distinto dependiendo del problema enfocado, de la escala y la etapa en la que se encuentre el proyecto.</p>
<p>Tal vez sea un prototipo visual a través de dibujos, esquemas o un diagrama o necesites un prototipo físico, desde una maqueta hasta un prototipo a escala real.</p>
<p>Muy posiblemente los prototipos para la solución del problema en el que estás trabajando irán creciendo en complejidad, empezando por dibujos simples, para ir evolucionando en representaciones más complejas.</p>
<p>Como estamos generando soluciones a través de un proceso iterativo, será necesario desarrollar y probar varios prototipos para ir mejorando el producto.</p>
<p>Un prototipo visual para las primeras etapas puede ser un dibujo simple sobre la idea, para después pasar a una historieta o comic sobre el producto o servicio y cómo es que el usuario interactúa con eso.</p>
<p>Si estás trabajando en un producto físico entonces será particularmente importante construir prototipos físicos para ir probando cómo funcionan las propuestas. Para algunos productos se realizan cientos de prototipos antes de su lanzamiento y se ponen a prueba para ver cuáles funcionan mejor.</p>
<p>Por ejemplo, para el caso de los creadores de Hyperloop, un nuevo sistema de transporte a través de tubos al vacío con cápsulas que viajan a altas velocidades, crear un primer prototipo implicó generar modelos a escala, y cada vez han ido creando modelos y prototipos más grandes hasta llegar a crear una pista de pruebas de más de un kilómetro en la que prueban cápsulas diseñadas por distintos grupos de ingenieros de todo el mundo.</p>
<p>Para el caso de mejorar la experiencia turística en una localidad dónde el impacto de llegada es relativamente malo en la terminal de autobuses, un prototipo podría ser algo tan sencillo como diseñar una manta con imágenes atractivas del destino, hasta realizar una maqueta o un entorno virtual para rediseñar toda una sección de la terminal.</p>
<p>En esta etapa de construcción del prototipo, se van identificando los elementos que podemos mejorar y qué tan viables son antes de tener un producto final.</p>
<p>Quizás durante el trabajo de construirlo, se obtiene nueva información que ayuda a comprender y empatizar con los usuarios, o te das cuenta que puedes redefinir cómo estás enfocando el problema y puedes abordarlo de una manera más eficiente, lo que potencialmente te haría regresar a las primeras fases, pero con mucho más conocimiento de causa y mejoras para el resultado final.</p>
<p>Por otro lado, antes de pulir demasiado los primeros prototipos, puede valer la pena poner a prueba algunos prototipos simples a los que evidentemente les hace falta trabajo para tratar de identificar si vamos por el camino correcto.</p>
<p>En este sentido, procura no agregar demasiados detalles a los prototipos iniciales, sino pensar sobre el problema desde una perspectiva más amplia.</p>
<h3>5. Prueba (Valida)</h3>
<figure class="wp-block-image size-large" style="margin: 0px 0px 1.5em; max-width: 100%; height: auto; color: #515151; font-family: Helvetica; font-size: 22px;"><img class="wp-image-97965 lazyloaded" style="height: auto; max-width: 100%;" src="https://identidadydesarrollo.com/wp-content/uploads/2019/07/Que%CC%81-es-el-paso-5-de-design-thinking-Prueba-1024x610.png" sizes="(max-width: 1024px) 100vw, 1024px" srcset="https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-5-de-design-thinking-Prueba-1024x610.png 1024w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-5-de-design-thinking-Prueba-300x179.png 300w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-5-de-design-thinking-Prueba-768x458.png 768w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-5-de-design-thinking-Prueba-1536x916.png 1536w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-5-de-design-thinking-Prueba-2048x1221.png 2048w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-5-de-design-thinking-Prueba-400x238.png 400w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-5-de-design-thinking-Prueba-600x358.png 600w" alt="" width="1024" height="610" data-src="https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-5-de-design-thinking-Prueba-1024x610.png" data-srcset="https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-5-de-design-thinking-Prueba-1024x610.png 1024w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-5-de-design-thinking-Prueba-300x179.png 300w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-5-de-design-thinking-Prueba-768x458.png 768w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-5-de-design-thinking-Prueba-1536x916.png 1536w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-5-de-design-thinking-Prueba-2048x1221.png 2048w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-5-de-design-thinking-Prueba-400x238.png 400w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-5-de-design-thinking-Prueba-600x358.png 600w"></figure>
<p>Ya que tenemos un prototipo es momento de ponerlo a prueba.</p>
<p>En esta fase vamos a desafiar nuestros diseños probándolos con distintos usuarios reales que tienen o podrían tener los problemas que nos proponemos solucionar.</p>
<p>La etapa de pruebas nos permite identificar mejoras fundamentales y posibles fallas del diseño y regresar a hacer ajustes en nuestros prototipos para seguir mejorando y puliendo el producto o servicio final.</p>
<p>Una opción interesante y altamente efectiva para probar nuestros diseños es a través de juegos de rol, simulacros o simulaciones con distintos tipos de personas y usuarios, incluyendo personas de nuestra comunidad, amigos o familiares.</p>
<p>Es importante tomar en cuenta que no se trata de realizar una prueba, sino múltiples pruebas para ir identificando lo que funciona y no funciona y realizar ajustes para volver a probar y mejorar la propuesta.</p>
<p>Tip pro:Realiza pruebas con distintos grupos de usuarios y considera que puedes realizar ajustes al prototipo rápidamente, hay quienes sugieren que inclusive puedes realizar ajustes durante la propia prueba si identificas que algo no está funcionando, especialmente si estás trabajando con una experiencia.</p>
<p>Hay que probar los prototipos tantas veces sea necesario hasta que tengamos una solución viable.</p>
<p>Durante todo el proceso debemos recordar que se trata de poner en duda nuestros paradigmas e ideas preconcebidas, por lo que es importante estar abiertos a nuevas posibilidades y no casarnos con una propuesta de solución única que parece viable en un principio o empujar nuestra propuesta con calzador para resolver el problema.</p>
<p>Lo más importante de esta etapa es realmente analizar cómo es que nuestros posibles usuarios interactúan y perciben nuestra solución para tener retroalimentación que nos permita mejorar nuestros prototipos y seguir probando con otros enfoques.</p>
<p>Recopilar los comentarios y percepciones de los usuarios, una de las mejores maneras es observar y tomar notas durante la prueba y posteriormente hacer preguntas abiertas que les permitan explayarse sobre su experiencia y no forzar su pensamiento a través de opción múltiple.</p>
<p >El resultado de las pruebas puede darnos nuevas ideas para abordar el problema o inclusive hasta hacernos pensar en direcciones completamente distintas que nos lleven a plantear un nuevo proyecto.</p>
<h3>6. Implementa</h3>
<figure class="wp-block-image size-large" style="margin: 0px 0px 1.5em; max-width: 100%; height: auto; color: #515151; font-family: Helvetica; font-size: 22px;"><img class="wp-image-97966 lazyloaded" style="height: auto; max-width: 100%;" src="https://identidadydesarrollo.com/wp-content/uploads/2019/07/Que%CC%81-es-el-paso-6-de-design-thinking-implementa-1024x610.jpg" sizes="(max-width: 1024px) 100vw, 1024px" srcset="https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-6-de-design-thinking-implementa-1024x610.jpg 1024w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-6-de-design-thinking-implementa-300x179.jpg 300w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-6-de-design-thinking-implementa-768x457.jpg 768w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-6-de-design-thinking-implementa-400x238.jpg 400w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-6-de-design-thinking-implementa-600x357.jpg 600w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-6-de-design-thinking-implementa.jpg 1026w" alt="Qué es el paso 6 de design thinking implementa" width="1024" height="610" data-src="https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-6-de-design-thinking-implementa-1024x610.jpg" data-srcset="https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-6-de-design-thinking-implementa-1024x610.jpg 1024w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-6-de-design-thinking-implementa-300x179.jpg 300w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-6-de-design-thinking-implementa-768x457.jpg 768w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-6-de-design-thinking-implementa-400x238.jpg 400w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-6-de-design-thinking-implementa-600x357.jpg 600w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Qué-es-el-paso-6-de-design-thinking-implementa.jpg 1026w"></figure>
<p>Una vez que se ha concluido la etapa de pruebas con resultados satisfactorios es momento de lanzar tu producto o servicio al mercado.</p>
<p>Lo más probable es que sigas identificando algunas oportunidades de mejora, idealmente anota todas esas pequeñas oportunidades y mantén la antena bien parada.</p>
<p>Si encuentras soluciones fáciles de implementar, en caso de que sea así, simplemente impleméntalas de manera continua.</p>
<p>En caso de que las oportunidades de mejora requieran una intervención más profunda, guarda un tiempo en el futuro para realizar otra iteración del proceso de diseño.</p>
<p>Es importante que establezcas indicadores relacionados con tus operaciones, así como la satisfacción y percepción de los clientes para asegurarte de que cuentes con información relevante para implementar cambios en el futuro y monitorear los impactos de esos cambios.</p>
<p>Para practicar el proceso hemos desarrollado un ejercicio de design thinking que te ayudará a empezar a experimentar.</p>
<h2>¿En qué puedo aplicar el proceso de design thinking?</h2>
<p>El pensamiento de diseño puede ser aplicado a cualquier ámbito de tu vida para resolver una infinidad de problemas.</p>
<p>Como toda habilidad, desarrollar habilidades de diseño requiere muchas horas de práctica, así que mientras más aplicas este tipo de ejercicios irás desarrollando mayores capacidades y competencias y lo harás cada vez mejor.</p>
<p>Si lo reflexionas, casi todo lo que hacemos se basa de una u otra forma en la resolución de problemas.</p>
<p>Entonces, si consideramos que el pensamiento de diseño es un enfoque que podemos aplicar a casi todo lo que hacemos, podrás incorporarlo a tu vida cotidiana y practicar constantemente para desarrollar tus capacidades en este sentido.</p>
<p>No pierdas el enfoque de lo que realmente estás buscando. Resolver el problema. Puede ser que con un producto o servicio que no sea completamente perfecto ya sea viable para poner lanzarlo al mercado. Por ejemplo. Si tienes un excelente café que múltiples clientes o clientes potenciales han probado, tal vez no convenga pasar demasiado tiempo buscando el empaque perfecto. Si la que tienes funciona para mantener su frescura y aroma, quizás sea suficiente para lanzarlo y empezar a generar ingresos para seguirlo mejorando.</p>
<p>En Identidad y Desarrollo, utilizamos el proceso de design thinking como complemento a nuestros<a style="border: 0px; margin: 0px; padding: 0px; background-color: transparent; transition: color 0.1s ease-in-out 0s, background-color 0.1s ease-in-out 0s; text-decoration-line: none; color: #296b6a;" href="https://identidadydesarrollo.com/modelo-de-alineacion-circular/">modelos de desarrollo de organizaciones y de destinos</a>, los cuales, hemos generado y probado a partir de la recolección de experiencias de trabajo en campo en distintos tipos de destinos.</p>
<h2 style="border: 0px; margin: 0px 0px 20px; padding: 0px; font-family: Helvetica; font-size: 40px; font-weight: normal; line-height: 1.2em; color: #515151;"><span id="La_espiral_de_aprendizaje_creativo" class="ez-toc-section" style="border: 0px; margin: 0px; padding: 0px;"></span>La espiral de aprendizaje creativo</h2>
<p style="border: 0px; margin: 0px 0px 1.5em; padding: 0px; color: #515151; font-family: Helvetica; font-size: 22px;">Mitchel Resnick, director del grupo de kínder de por vida del MIT Media Lab, relaciona el pensamiento de diseño con el planteamiento de una espiral de aprendizaje creativo, que propone un esquema de aprendizaje a través del juego colaborativo.</p>
<div>
<figure class="aligncenter size-large" style="display: table; margin: 0px auto; clear: both; max-width: 100%; height: auto;"><img class="wp-image-97968 lazyloaded" style="height: auto; max-width: 100%;" src="https://identidadydesarrollo.com/wp-content/uploads/2019/07/Espiral-de-aprendizaje-creativo-de-design-thinking.jpg" sizes="(max-width: 526px) 100vw, 526px" srcset="https://identidadydesarrollo.com/wp-content/uploads/2019/07/Espiral-de-aprendizaje-creativo-de-design-thinking.jpg 526w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Espiral-de-aprendizaje-creativo-de-design-thinking-300x256.jpg 300w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Espiral-de-aprendizaje-creativo-de-design-thinking-352x300.jpg 352w" alt="" width="526" height="448" data-src="https://identidadydesarrollo.com/wp-content/uploads/2019/07/Espiral-de-aprendizaje-creativo-de-design-thinking.jpg" data-srcset="https://identidadydesarrollo.com/wp-content/uploads/2019/07/Espiral-de-aprendizaje-creativo-de-design-thinking.jpg 526w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Espiral-de-aprendizaje-creativo-de-design-thinking-300x256.jpg 300w, https://identidadydesarrollo.com/wp-content/uploads/2019/07/Espiral-de-aprendizaje-creativo-de-design-thinking-352x300.jpg 352w">
<figcaption style="display: table-caption; margin-top: 0.5em; margin-bottom: 1em; caption-side: bottom;">Basado en Mitchel Resnick, grupo de kinder de por vida de MIT Media Lab 2018</figcaption>
</figure>
</div>
<p>Es una espiral y no un ciclo, ya que empieza con la imaginación y a partir de las creaciones, juegos y reflexiones se llega a nuevas ideas creativas con un mayor conocimiento del que se tenía antes, quizás encontrando nuevas problemáticas y necesidades que no habíamos identificado.</p>
<h2>Un buen producto o servicio puede cambiar la manera en la que el usuario interactúa con un objeto o con su entorno</h2>
<p>Si buscamos incidir en la manera en las personas que perciben el mundo o cómo interactúan con el ambiente para minimizar su impacto, podemos abordar el diseño de productos y servicios incorporando una perspectiva educativa de manera innovadora.</p>
<p>Esto es particularmente importante en el sector turístico y cultural, que se relacionan con experiencias vivenciales en las que los visitantes o “consumidores” suelen tener cierta apertura mental al estar en un entorno fuera del habitual.</p>
<p><span style="border: 0px; margin: 0px; padding: 0px; font-weight: bold;">Reflexiona sobre las siguientes preguntas:</span></p>
<p>¿Cómo cambiamos la manera en que nos aproximamos a los turistas?</p>
<p>¿Por qué se comporta de una manera particular o entiende algo específico, podemos identificar brechas?</p>
<p>¿Podemos comunicar la importancia de ser más responsables con el entorno, el medio ambiente de una forma que conquiste la curiosidad y el interés de nuestros visitantes?</p>
<p>Una manera que quizás puede parecer obvia, podría ser establecer reglas claras de comportamiento en nuestros destinos o en ciertos espacios y comunicarlas de manera clara, como la etiqueta de vestimenta para la entrada a templos para ser respetuosos de las costumbres locales, o mantenerse dentro de los senderos en un área natural para evitar impactar las especies de flora y fauna de las que quizás no estamos tan conscientes, pero ahí están.</p>
<p>Con estos ejemplos ¿cómo harías para promover el tipo de comportamiento que buscas? ¿Con señalética? ¿Con una inducción previa o necesidad de contar con un guía de manera obligatoria para entrar a ciertos lugares?</p>
<p>Tal vez encuentres respuestas fáciles a estas respuestas, o te den ganas de implementarlas todas de una vez, aunque seguramente surgirían otras necesidades y problemas para implementarlas.</p>
<p>Tomando el ejemplo de la señalética, ¿con qué recursos se va a desarrollar el proyecto? ¿Necesitamos permiso de alguna institución u organización para implementarla? ¿Quién va a diseñarla, fabricarla o instalarla?</p>
<div class="wp-block-image" style="border: 0px; margin: 0px 0px 1.5em; padding: 0px; color: #515151; font-family: Helvetica; font-size: 22px;">
<figure class="aligncenter size-large" style="display: table; margin: 0px auto; clear: both; max-width: 100%; height: auto;"><img class="wp-image-320 lazyloaded" style="height: auto; max-width: 100%;" src="https://identidadydesarrollo.com/wp-content/uploads/2015/06/welcome-sign-760358_640.jpg" sizes="(max-width: 640px) 100vw, 640px" srcset="https://identidadydesarrollo.com/wp-content/uploads/2015/06/welcome-sign-760358_640.jpg 640w, https://identidadydesarrollo.com/wp-content/uploads/2015/06/welcome-sign-760358_640-600x338.jpg 600w, https://identidadydesarrollo.com/wp-content/uploads/2015/06/welcome-sign-760358_640-300x169.jpg 300w" alt="Letrero de bienvenida" width="640" height="360" data-src="https://identidadydesarrollo.com/wp-content/uploads/2015/06/welcome-sign-760358_640.jpg" data-srcset="https://identidadydesarrollo.com/wp-content/uploads/2015/06/welcome-sign-760358_640.jpg 640w, https://identidadydesarrollo.com/wp-content/uploads/2015/06/welcome-sign-760358_640-600x338.jpg 600w, https://identidadydesarrollo.com/wp-content/uploads/2015/06/welcome-sign-760358_640-300x169.jpg 300w"></figure>
</div>
<p>Por otro lado, si optamos por generar un proceso de inducción para la entrada a un área cultural o natural, necesitaremos tener una persona que haga siempre la bienvenida y podría estar ocupada con otras funciones. ¿O no realmente? ¿Podemos generar un video y compartirlo con los visitantes a la llegada?</p>
<p>Puede haber muchas fórmulas para cumplir con un mismo objetivo, por lo que la solución dependerá del enfoque, los recursos, incluyendo las habilidades y conocimientos de quienes van a implementarla y la creatividad local para aprovechar esos recursos de manera efectiva.</p>
<p>Algo que me gusta mucho sobre el pensamiento de diseño y la innovación tanto en comunidades urbanas como rurales es que me parece que tiene un amplio potencial para promover la incorporación de las y los jóvenes en las esferas de gestión y toma de decisiones que tradicionalmente suelen incorporar solo a ciertos sectores de la población.</p>
<h2>Considerando las restricciones, requerimientos y libertades creativas</h2>
<p>Conforme avances en el análisis del problema y las propuestas de solución a través del proceso de design thinking, encontrarás que muchas veces los problemas que encontramos son complejos, y presentan situaciones que están fuera de tu capacidad de incidencia así que no necesariamente podrás identificar una solución rápidamente.</p>
<p>Sin embargo, si partes el problema en otros problemas más pequeños y revisamos las restricciones o limitantes, los requerimientos y las libertades creativas del entorno, podremos ir generando soluciones creativas adecuadas a cada situación.</p>
<p>Procura analizar todas las características del entorno para identificar este tipo de cosas.</p>
<p>Las restricciones o condiciones limitantes son las cosas que no puedes cambiar en el entorno en el que estás trabajando y que pueden afectar la solución. Por ejemplo, una accesibilidad limitada o caminos en malas condiciones que salgan de los alcances del proyecto.</p>
<p>También hay requerimientos, que pueden ser algunos elementos mínimos para nuestra solución, siguiendo con el caso de una construcción podríamos pensar en que se requiere una cimentación mínima dependiendo de la estructura que se piense utilizar.</p>
<p>Las libertades creativas, son lo opuesto a las restricciones, como una alta disponibilidad de energía solar en el sitio, que podrías aprovechar de distintas maneras.</p>
<p>Créditos:</p>
<p>Para escribir este artículo, me base principalmente en la experiencia práctica obtenida como colaborador de identidad y desarrollo, bajo el liderazgo de Alejandra Zorrilla, las enseñanzas de mis maestros de la Facultad de Diseño Ambiental de la Universidad de Calgary, como Barry Wylant y Noel Keough, así como el curso de imagina para el pensamiento de diseño creado por el Laboratorio de Sistemas de Aprendizaje del MITCourse Image for Design Thinking for Leading and Learning” by MIT Teaching Systems Lab  registrado bajo la licencia Creative Commons CC BY 4.0.</p>
